<template>
  <div class="result">
      <el-tabs type="border-card" v-model="name">
          <div label="演讲主题词云图" name="2" ref="chart3" style="width: 100%;height:550px"></div>
      </el-tabs>
  </div>
</template>

<script>
import * as echarts from "echarts";
import "./js/echarts";
import "./js/echarts-wordcloud.min";

export default {
  name: "VisitShow",
  data() {
    return {
      userVisitNum: [],
      date: [],
      goodVisitNum: [],
      goodsName: [],
      name: "0",
    };
  },
  mounted() {
    this.showEeharts();
  },

  methods: {
    showEeharts() {
      var chart3 = echarts.init(this.$refs.chart3);

      var data3 = [{name:'technology', value: 727},
  	{name:" science", value: 567},
  	{name:" globalissues", value: 501},
  	{name:" culture", value: 486},
  	{name:" TEDx", value: 450},
  	{name:" design", value: 418},
  	{name:" business", value: 348},
  	{name:" entertainment", value: 299},
  	{name:" health", value: 236},
  	{name:" innovation", value: 229},
  	{name:" society", value: 224},
  	{name:" art", value: 221},
  	{name:" socialchange", value: 218},
  	{name:" future", value: 195},
  	{name:" communication", value: 191},
  	{name:" biology", value: 189},
  	{name:" creativity", value: 189},
  	{name:" humanity", value: 182},
  	{name:" collaboration", value: 174},
  	{name:" environment", value: 165},
  	{name:" economics", value: 164},
  	{name:" medicine", value: 162},
  	{name:" brain", value: 158},
  	{name:" activism", value: 157},
  	{name:" education", value: 153},
  	{name:" community", value: 148},
  	{name:" history", value: 146},
  	{name:" children", value: 143},
  	{name:" TEDFellows", value: 143},
  	{name:" music", value: 140},
  	{name:" invention", value: 140},
  	{name:" healthcare", value: 132},
  	{name:" politics", value: 128},
  	{name:" cities", value: 123},
  	{name:" psychology", value: 122},
  	{name:" storytelling", value: 120},
  	{name:" performance", value: 117},
  	{name:" women", value: 117},
  	{name:" nature", value: 116},
  	{name:" identity", value: 113},
  	{name:" war", value: 113},
  	{name:" life", value: 111},
  	{name:" engineering", value: 111},
  	{name:" computers", value: 111},
  	{name:" animals", value: 109},
  	{name:" Africa", value: 105},
  	{name:" humor", value: 105},
  	{name:" exploration", value: 100},
  	{name:" personalgrowth", value: 96},
  	{name:" inequality", value: 94},
  	{name:" data", value: 94},
  	{name:" government", value: 93},
  	{name:" photography", value: 92},
  	{name:" medicalresearch", value: 92},
  	{name:" neuroscience", value: 89},
  	{name:" climatechange", value: 87},
  	{name:" work", value: 85},
  	{name:" Internet", value: 84},
  	{name:" visualizations", value: 83},
  	{name:" architecture", value: 82},
  	{name:" livemusic", value: 80},
  	{name:" sustainability", value: 80},
  	{name:" disease", value: 79},
  	{name:" oceans", value: 77},
  	{name:" physics", value: 75},
  	{name:" happiness", value: 73},
  	{name:" potential", value: 73},
  	{name:" green", value: 73},
  	{name:" biotech", value: 72},
  	{name:" mind", value: 71},
  	{name:" violence", value: 69},
  	{name:" evolution", value: 68},
  	{name:" media", value: 68},
  	{name:" film", value: 67},
  	{name:" writing", value: 67},
  	{name:" bigproblems", value: 65},
  	{name:" globaldevelopment", value: 64},
  	{name:" philosophy", value: 64},
  	{name:" entrepreneur", value: 64},
  	{name:" beauty", value: 63},
  	{name:" motivation", value: 63},
  	{name:" genetics", value: 62},
  	{name:" biodiversity", value: 62},
  	{name:" space", value: 60},
  	{name:" language", value: 59},
  	{name:" robots", value: 59},
  	{name:" mentalhealth", value: 59},
  	{name:" poverty", value: 59},
  	{name:" cognitivescience", value: 58},
  	{name:" food", value: 57},
  	{name:" math", value: 57},
  	{name:" religion", value: 56},
  	{name:" family", value: 54},
  	{name:" ecology", value: 54},
  	{name:" peace", value: 54},
  	{name:" poetry", value: 53},
  	{name:" demo", value: 53},
  	{name:" illness", value: 53},
  	{name:" universe", value: 52},
  	{name:" socialmedia", value: 52},
  	{name:" energy", value: 52},
  	{name:" policy", value: 51},
  	{name:" productdesign", value: 51},
  	{name:" self", value: 50},
  	{name:" parenting", value: 50},
  	{name:" intelligence", value: 50},
  	{name:" journalism", value: 50},
  	{name:" TEDBrainTrust", value: 49},
  	{name:" infrastructure", value: 49},
  	{name:" law", value: 48},
  	{name:" adventure", value: 48},
  	{name:" astronomy", value: 48},
  	{name:" comedy", value: 48},
  	{name:" democracy", value: 47},
  	{name:" publichealth", value: 47},
  	{name:" cancer", value: 47},
  	{name:" DNA", value: 46},
  	{name:" software", value: 45},
  	{name:" crime", value: 44},
  	{name:" leadership", value: 44},
  	{name:" death", value: 44},
  	{name:" web", value: 43},
  	{name:" teaching", value: 43},
  	{name:" AI", value: 43},
  	{name:" aging", value: 43},
  	{name:" race", value: 43},
  	{name:" choice", value: 42},
  	{name:" scienceandart", value: 42},
  	{name:" water", value: 41},
  	{name:" security", value: 40},
  	{name:" love", value: 39},
  	{name:" pollution", value: 39},
  	{name:" materials", value: 39},
  	{name:" youth", value: 38},
  	{name:" algorithm", value: 38},
  	{name:" chemistry", value: 38},
  	{name:" terrorism", value: 38},
  	{name:" alternativeenergy", value: 37},
  	{name:" transportation", value: 36},
  	{name:" making", value: 36},
  	{name:" agriculture", value: 36},
  	{name:" decision", value: 36},
  	{name:" goal", value: 36},
  	{name:" setting", value: 36},
  	{name:" books", value: 36},
  	{name:" compassion", value: 35},
  	{name:" insects", value: 35},
  	{name:" source", value: 34},
  	{name:" Genderequality", value: 34},
  	{name:" disability", value: 34},
  	{name:" open", value: 34},
  	{name:" sex", value: 34},
  	{name:" philanthropy", value: 33},
  	{name:" investment", value: 32},
  	{name:" money", value: 32},
  	{name:" molecularbiology", value: 32},
  	{name:" MiddleEast", value: 32},
  	{name:" gaming", value: 31},
  	{name:" sports", value: 31},
  	{name:" fear", value: 31},
  	{name:" microbiology", value: 31},
  	{name:" biomechanics", value: 30},
  	{name:" UnitedStates", value: 30},
  	{name:" curiosity", value: 30},
  	{name:" industrialdesign", value: 29},
  	{name:" feminism", value: 29},
  	{name:" urbanplanning", value: 29},
  	{name:" relationships", value: 29},
  	{name:" plants", value: 28},
  	{name:" success", value: 28},
  	{name:" statistics", value: 28},
  	{name:" fish", value: 28},
  	{name:" interfacedesign", value: 28},
  	{name:" TEDPrize", value: 27},
  	{name:" bacteria", value: 27},
  	{name:" gender", value: 27},
  	{name:" Planets", value: 27},
  	{name:" empathy", value: 26},
  	{name:" Asia", value: 26},
  	{name:" womeninbusiness", value: 26},
  	{name:" code", value: 25},
  	{name:" depression", value: 25},
  	{name:" dance", value: 25},
  	{name:" disasterrelief", value: 25},
  	{name:" TEDYouth", value: 24},
  	{name:" nanoscale", value: 24},
  	{name:" consciousness", value: 24},
  	{name:" faith", value: 24},
  	{name:" anthropology", value: 23},
  	{name:" onlinevideo", value: 23},
  	{name:" Bioethics", value: 23},
  	{name:" performanceart", value: 23},
  	{name:" physiology", value: 23},
  	{name:" memory", value: 23},
  	{name:" garden", value: 23},
  	{name:" behavioraleconomics", value: 23},
  	{name:" Senses", value: 23},
  	{name:" morality", value: 22},
  	{name:" biomimicry", value: 22},
  	{name:" corruption", value: 22},
  	{name:" missionblue", value: 22},
  	{name:" ancientworld", value: 22},
  	{name:" consumerism", value: 22},
  	{name:" personality", value: 21},
  	{name:" sociology", value: 21},
  	{name:" literature", value: 21},
  	{name:" pharmaceuticals", value: 21},
  	{name:" sight", value: 21},
  	{name:" Surveillance", value: 21},
  	{name:" china", value: 21},
  	{name:" marketing", value: 21},
  	{name:" NASA", value: 21},
  	{name:" programming", value: 20},
  	{name:" illusion", value: 20},
  	{name:" cars", value: 20},
  	{name:" military", value: 20},
  	{name:" productivity", value: 20},
  	{name:" TEDMED", value: 19},
  	{name:" worldcultures", value: 19},
  	{name:" TEDNYC", value: 19},
  	{name:" prison", value: 19},
  	{name:" news", value: 19},
  	{name:" play", value: 18},
  	{name:" sound", value: 18},
  	{name:" drones", value: 18},
  	{name:" publicspaces", value: 18},
  	{name:" telescopes", value: 18},
  	{name:" Europe", value: 18},
  	{name:" machinelearning", value: 18},
  	{name:" movies", value: 18},
  	{name:" library", value: 18},
  	{name:" magic", value: 18},
  	{name:" complexity", value: 18},
  	{name:" finance", value: 17},
  	{name:" prosthetics", value: 17},
  	{name:" guitar", value: 17},
  	{name:" time", value: 17},
  	{name:" solarsystem", value: 17},
  	{name:" singer", value: 17},
  	{name:" india", value: 17},
  	{name:" TEDBooks", value: 17},
  	{name:" manufacturing", value: 16},
  	{name:" microbes", value: 16},
  	{name:" cosmos", value: 16},
  	{name:" God", value: 16},
  	{name:" privacy", value: 16},
  	{name:" animation", value: 16},
  	{name:" AIDS", value: 16},
  	{name:" theater", value: 16},
  	{name:" map", value: 16},
  	{name:" solarenergy", value: 16},
  	{name:" conservation", value: 15},
  	{name:" flight", value: 15},
  	{name:" speech", value: 15},
  	{name:" piano", value: 15},
  	{name:" hearthealth", value: 15},
  	{name:" spokenword", value: 15},
  	{name:" trees", value: 15},
  	{name:" botany", value: 15},
  	{name:" toy", value: 15},
  	{name:" simplicity", value: 14},
  	{name:" sanitation", value: 14},
  	{name:" SouthAmerica", value: 14},
  	{name:" presentation", value: 14},
  	{name:" failure", value: 14},
  	{name:" fashion", value: 14},
  	{name:" LGBT", value: 14},
  	{name:" immigration", value: 14},
  	{name:" Anthropocene", value: 14},
  	{name:" Egypt", value: 14},
  	{name:" interview", value: 14},
  	{name:" lifebalance", value: 14},
  	{name:" extraterrestriallife", value: 14},
  	{name:" virtualreality", value: 14},
  	{name:" MacArthurgrant", value: 13},
  	{name:" museums", value: 13},
  	{name:" weather", value: 13},
  	{name:" protests", value: 13},
  	{name:" Surgery", value: 13},
  	{name:" darkmatter", value: 13},
  	{name:" syntheticbiology", value: 13},
  	{name:" prediction", value: 13},
  	{name:" capitalism", value: 13},
  	{name:" TEDenEspa", value: 12},
  	{name:" Blindness", value: 12},
  	{name:" birds", value: 12},
  	{name:" Mars", value: 12},
  	{name:" virus", value: 12},
  	{name:" population", value: 12},
  	{name:" discovery", value: 12},
  	{name:" refugees", value: 12},
  	{name:" hack", value: 12},
  	{name:" iraq", value: 12},
  	{name:" Vaccines", value: 12},
  	{name:" Naturalresources", value: 12},
  	{name:" ol", value: 12},
  	{name:" medicalimaging", value: 11},
  	{name:" astrobiology", value: 11},
  	{name:" TED", value: 11},
  	{name:" trust", value: 11},
  	{name:" bees", value: 11},
  	{name:" humanorigins", value: 11},
  	{name:" bodylanguage", value: 11},
  	{name:" Ed", value: 11},
  	{name:" ebola", value: 11},
  	{name:" obesity", value: 11},
  	{name:" friendship", value: 11},
  	{name:" composing", value: 11},
  	{name:" farming", value: 10},
  	{name:" dinosaurs", value: 10},
  	{name:" Slavery", value: 10},
  	{name:" sexualviolence", value: 10},
  	{name:" evolutionarypsychology", value: 10},
  	{name:" nuclearenergy", value: 10},
  	{name:" Autismspectrumdisorder", value: 10},
  	{name:" advertising", value: 10},
  	{name:" travel", value: 10},
  	{name:" plastic", value: 10},
  	{name:" Brazil", value: 10},
  	{name:" naturaldisaster", value: 10},
  	{name:" Google", value: 10},
  	{name:" Stringtheory", value: 10},
  	{name:" CriminalJustice", value: 10},
  	{name:" paleontology", value: 10},
  	{name:" PTSD", value: 10},
  	{name:" submarine", value: 10},
  	{name:" Humanbody", value: 10},
  	{name:" bigbang", value: 9},
  	{name:" driverlesscars", value: 9},
  	{name:" smell", value: 9},
  	{name:" vocals", value: 9},
  	{name:" men", value: 9},
  	{name:" archaeology", value: 9},
  	{name:" crowdsourcing", value: 9},
  	{name:" pain", value: 9},
  	{name:" Islam", value: 9},
  	{name:" Syria", value: 8},
  	{name:" suicide", value: 8},
  	{name:" wikipedia", value: 8},
  	{name:" telecom", value: 8},
  	{name:" NewYork", value: 8},
  	{name:" painting", value: 8},
  	{name:" rivers", value: 8},
  	{name:" ForeignPolicy", value: 8},
  	{name:" charterforcompassion", value: 8},
  	{name:" rocketscience", value: 8},
  	{name:" pregnancy", value: 8},
  	{name:" windenergy", value: 7},
  	{name:" aircraft", value: 7},
  	{name:" bullying", value: 7},
  	{name:" narcotics", value: 7},
  	{name:" shopping", value: 7},
  	{name:" Debate", value: 7},
  	{name:" extremesports", value: 7},
  	{name:" conducting", value: 7},
  	{name:" mobility", value: 7},
  	{name:" biosphere", value: 7},
  	{name:" meditation", value: 7},
  	{name:" deextinction", value: 7},
  	{name:" Transgender", value: 7},
  	{name:" monkeys", value: 7},
  	{name:" Buddhism", value: 7},
  	{name:" student", value: 6},
  	{name:" typography", value: 6},
  	{name:" HIV", value: 6},
  	{name:" cyborg", value: 6},
  	{name:" Guns", value: 6},
  	{name:" trafficking", value: 6},
  	{name:" Alzheimers", value: 6},
  	{name:" Genderspectrum", value: 6},
  	{name:" Christianity", value: 6},
  	{name:" TEDResidency", value: 6},
  	{name:" geology", value: 6},
  	{name:" violin", value: 6},
  	{name:" primates", value: 6},
  	{name:" nonviolence", value: 6},
  	{name:" exoskeleton", value: 6},
  	{name:" wunderkind", value: 6},
  	{name:" hearing", value: 5},
  	{name:" asteroid", value: 5},
  	{name:" meme", value: 5},
  	{name:" atheism", value: 5},
  	{name:" mindfulness", value: 5},
  	{name:" oil", value: 5},
  	{name:" resources", value: 5},
  	{name:" Iran", value: 5},
  	{name:" introvert", value: 5},
  	{name:" state", value: 5},
  	{name:" Addiction", value: 5},
  	{name:" television", value: 5},
  	{name:" building", value: 5},
  	{name:" ants", value: 4},
  	{name:" jazz", value: 4},
  	{name:" vulnerability", value: 4},
  	{name:" glacier", value: 4},
  	{name:" urban", value: 4},
  	{name:" microfinance", value: 4},
  	{name:" nuclearweapons", value: 4},
  	{name:" CRISPR", value: 4},
  	{name:" sleep", value: 4},
  	{name:" Moon", value: 3},
  	{name:" streetart", value: 3},
  	{name:" pandemic", value: 3},
  	{name:" 3dprinting", value: 3},
  	{name:" microsoft", value: 3},
  	{name:" cello", value: 3},
  	{name:" novel", value: 3},
  	{name:" apes", value: 3},
  	{name:" blockchain", value: 3},
  	{name:" Nobelprize", value: 3},
  	{name:" forensics", value: 3},
  	{name:" epidemiology", value: 3},
  	{name:" Brand", value: 3},
  	{name:" mining", value: 3},
  	{name:" origami", value: 2},
  	{name:" evil", value: 2},
  	{name:" grammar", value: 2},
  	{name:" augmentedreality", value: 2},
  	{name:" skateboarding", value: 1},
  	{name:" funny", value: 1},
  	{name:" cloud", value: 1},
  	{name:" testing", value: 1},
    ]

      var chart3Option = {
          title: {
              text: '演讲主题词云图',//标题
              x: 'center',
              textStyle: {
                  fontSize: 23
              }

          },
          backgroundColor: '#fff',
          tooltip: {
              show: true
          },
          series: [{
              name: '演讲主题词云图',//数据提示窗标题
              type: 'wordCloud',
              sizeRange: [12, 64],//画布范围，如果设置太大会出现少词（溢出屏幕）
              rotationRange: [-45, 90],//数据翻转范围
              //shape: 'circle',
              textPadding: 0,
              autoSize: {
                  enable: true,
                  minSize: 6
              },
              textStyle: {
                  normal: {
                      color: function() {
                          console.log('rgb(' + [
                              Math.round(Math.random() * 160),
                              Math.round(Math.random() * 160),
                              Math.round(Math.random() * 160)
                          ].join(',') + ')')
                          return 'rgb(' + [
                              Math.round(Math.random() * 160),
                              Math.round(Math.random() * 160),
                              Math.round(Math.random() * 160)
                          ].join(',') + ')';
                      }
                  },
                  emphasis: {
                      shadowBlur: 10,
                      shadowColor: '#333'
                  }
              },
              data: data3,
          }]
      };

      chart3.setOption(chart3Option);
    },
  },
};
</script>
<style lang="less">

</style>
